### ISSUE TITLE
build native failed

### ISSUE THREAD

**Issue by itboy87** [angrymango/quarkus-ext-jooq#1]
Hi tried it by creating new project. Project build successfully but when I try to build native then it failed.
I'm using it with gradle and building native with following command
`./gradlew build -Dquarkus.package.type=native`

But getting this error:

```
Error: Unsupported features in 4 methods
Detailed message:
Error: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved type during parsing: javax.persistence.Column. To diagnose the issue you can use the --allow-incomplete-classpath option. The missing type is then reported at run time when it is accessed the first time.
Trace: 
        at parsing org.jooq.impl.Tools$6.apply(Tools.java:3440)
Call path from entry point to org.jooq.impl.Tools$6.apply(): 
        at org.jooq.impl.Tools$6.apply(Tools.java:3437)
        at org.jooq.impl.Tools$6.apply(Tools.java:3433)
        at org.jooq.impl.Tools$Cache.run(Tools.java:3181)
        at org.jooq.impl.DefaultRecordMapperProvider.provide(DefaultRecordMapperProvider.java:83)
        at com.oracle.svm.reflect.DefaultRecordMapperProvider_provide_1f8963e2e741d6be3b1656e5266fd0d5676700fe_576.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Method.java:566)
        at org.jboss.resteasy.core.ContextParameterInjector$GenericDelegatingProxy.invoke(ContextParameterInjector.java:122)
        at com.sun.proxy.$Proxy258.hashCode(Unknown Source)
        at java.util.HashMap.hash(HashMap.java:339)
        at java.util.HashMap.get(HashMap.java:552)
        at com.oracle.svm.jni.access.JNIReflectionDictionary.getClassObjectByName(JNIReflectionDictionary.java:128)
        at com.oracle.svm.jni.functions.JNIFunctions.FindClass(JNIFunctions.java:324)
        at com.oracle.svm.core.code.IsolateEnterStub.JNIFunctions_FindClass_3ec1032c6cb9443725d1e68194130533bfb04076(generated:0)
Error: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved type during parsing: javax.persistence.Column. To diagnose the issue you can use the --allow-incomplete-classpath option. The missing type is then reported at run time when it is accessed the first time.
Trace: 
        at parsing org.jooq.impl.Tools$8.apply(Tools.java:3507)
Call path from entry point to org.jooq.impl.Tools$8.apply(): 
        at org.jooq.impl.Tools$8.apply(Tools.java:3504)
        at org.jooq.impl.Tools$8.apply(Tools.java:3500)
        at org.jooq.impl.Tools$Cache.run(Tools.java:3181)
        at org.jooq.impl.DefaultRecordMapperProvider.provide(DefaultRecordMapperProvider.java:83)
        at com.oracle.svm.reflect.DefaultRecordMapperProvider_provide_1f8963e2e741d6be3b1656e5266fd0d5676700fe_576.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Method.java:566)
        at org.jboss.resteasy.core.ContextParameterInjector$GenericDelegatingProxy.invoke(ContextParameterInjector.java:122)
        at com.sun.proxy.$Proxy258.hashCode(Unknown Source)
        at java.util.HashMap.hash(HashMap.java:339)
        at java.util.HashMap.get(HashMap.java:552)
        at com.oracle.svm.jni.access.JNIReflectionDictionary.getClassObjectByName(JNIReflectionDictionary.java:128)
        at com.oracle.svm.jni.functions.JNIFunctions.FindClass(JNIFunctions.java:324)
        at com.oracle.svm.core.code.IsolateEnterStub.JNIFunctions_FindClass_3ec1032c6cb9443725d1e68194130533bfb04076(generated:0)
Error: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved type during parsing: javax.persistence.Column. To diagnose the issue you can use the --allow-incomplete-classpath option. The missing type is then reported at run time when it is accessed the first time.
Trace: 
        at parsing org.jooq.impl.Tools$9.apply(Tools.java:3556)
Call path from entry point to org.jooq.impl.Tools$9.apply(): 
        at org.jooq.impl.Tools$9.apply(Tools.java:3555)
        at org.jooq.impl.Tools$9.apply(Tools.java:3551)
        at org.jooq.impl.Tools$Cache.run(Tools.java:3181)
        at org.jooq.impl.DefaultRecordMapperProvider.provide(DefaultRecordMapperProvider.java:83)
        at com.oracle.svm.reflect.DefaultRecordMapperProvider_provide_1f8963e2e741d6be3b1656e5266fd0d5676700fe_576.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Method.java:566)
        at org.jboss.resteasy.core.ContextParameterInjector$GenericDelegatingProxy.invoke(ContextParameterInjector.java:122)
        at com.sun.proxy.$Proxy258.hashCode(Unknown Source)
        at java.util.HashMap.hash(HashMap.java:339)
        at java.util.HashMap.get(HashMap.java:552)
        at com.oracle.svm.jni.access.JNIReflectionDictionary.getClassObjectByName(JNIReflectionDictionary.java:128)
        at com.oracle.svm.jni.functions.JNIFunctions.FindClass(JNIFunctions.java:324)
        at com.oracle.svm.core.code.IsolateEnterStub.JNIFunctions_FindClass_3ec1032c6cb9443725d1e68194130533bfb04076(generated:0)
Error: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved type during parsing: javax.persistence.Entity. To diagnose the issue you can use the --allow-incomplete-classpath option. The missing type is then reported at run time when it is accessed the first time.
Trace: 
        at parsing org.jooq.impl.Tools$5.apply(Tools.java:3405)
Call path from entry point to org.jooq.impl.Tools$5.apply(): 
        at org.jooq.impl.Tools$5.apply(Tools.java:3401)
        at org.jooq.impl.Tools$5.apply(Tools.java:3397)
        at org.jooq.impl.Tools$Cache.run(Tools.java:3181)
        at org.jooq.impl.DefaultRecordMapperProvider.provide(DefaultRecordMapperProvider.java:83)
        at com.oracle.svm.reflect.DefaultRecordMapperProvider_provide_1f8963e2e741d6be3b1656e5266fd0d5676700fe_576.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Method.java:566)
        at org.jboss.resteasy.core.ContextParameterInjector$GenericDelegatingProxy.invoke(ContextParameterInjector.java:122)
        at com.sun.proxy.$Proxy258.hashCode(Unknown Source)
        at java.util.HashMap.hash(HashMap.java:339)
        at java.util.HashMap.get(HashMap.java:552)
        at com.oracle.svm.jni.access.JNIReflectionDictionary.getClassObjectByName(JNIReflectionDictionary.java:128)
        at com.oracle.svm.jni.functions.JNIFunctions.FindClass(JNIFunctions.java:324)
        at com.oracle.svm.core.code.IsolateEnterStub.JNIFunctions_FindClass_3ec1032c6cb9443725d1e68194130533bfb04076(generated:0)

com.oracle.svm.core.util.UserError$UserException: Unsupported features in 4 methods
Detailed message:
Error: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved type during parsing: javax.persistence.Column. To diagnose the issue you can use the --allow-incomplete-classpath option. The missing type is then reported at run time when it is accessed the first time.
Trace: 
        at parsing org.jooq.impl.Tools$6.apply(Tools.java:3440)
Call path from entry point to org.jooq.impl.Tools$6.apply(): 
        at org.jooq.impl.Tools$6.apply(Tools.java:3437)
        at org.jooq.impl.Tools$6.apply(Tools.java:3433)
        at org.jooq.impl.Tools$Cache.run(Tools.java:3181)
        at org.jooq.impl.DefaultRecordMapperProvider.provide(DefaultRecordMapperProvider.java:83)
        at com.oracle.svm.reflect.DefaultRecordMapperProvider_provide_1f8963e2e741d6be3b1656e5266fd0d5676700fe_576.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Method.java:566)
        at org.jboss.resteasy.core.ContextParameterInjector$GenericDelegatingProxy.invoke(ContextParameterInjector.java:122)
        at com.sun.proxy.$Proxy258.hashCode(Unknown Source)
        at java.util.HashMap.hash(HashMap.java:339)
        at java.util.HashMap.get(HashMap.java:552)
        at com.oracle.svm.jni.access.JNIReflectionDictionary.getClassObjectByName(JNIReflectionDictionary.java:128)
        at com.oracle.svm.jni.functions.JNIFunctions.FindClass(JNIFunctions.java:324)
        at com.oracle.svm.core.code.IsolateEnterStub.JNIFunctions_FindClass_3ec1032c6cb9443725d1e68194130533bfb04076(generated:0)
Error: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved type during parsing: javax.persistence.Column. To diagnose the issue you can use the --allow-incomplete-classpath option. The missing type is then reported at run time when it is accessed the first time.
Trace: 
        at parsing org.jooq.impl.Tools$8.apply(Tools.java:3507)
Call path from entry point to org.jooq.impl.Tools$8.apply(): 
        at org.jooq.impl.Tools$8.apply(Tools.java:3504)
        at org.jooq.impl.Tools$8.apply(Tools.java:3500)
        at org.jooq.impl.Tools$Cache.run(Tools.java:3181)
        at org.jooq.impl.DefaultRecordMapperProvider.provide(DefaultRecordMapperProvider.java:83)
        at com.oracle.svm.reflect.DefaultRecordMapperProvider_provide_1f8963e2e741d6be3b1656e5266fd0d5676700fe_576.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Method.java:566)
        at org.jboss.resteasy.core.ContextParameterInjector$GenericDelegatingProxy.invoke(ContextParameterInjector.java:122)
        at com.sun.proxy.$Proxy258.hashCode(Unknown Source)
        at java.util.HashMap.hash(HashMap.java:339)
        at java.util.HashMap.get(HashMap.java:552)
        at com.oracle.svm.jni.access.JNIReflectionDictionary.getClassObjectByName(JNIReflectionDictionary.java:128)
        at com.oracle.svm.jni.functions.JNIFunctions.FindClass(JNIFunctions.java:324)
        at com.oracle.svm.core.code.IsolateEnterStub.JNIFunctions_FindClass_3ec1032c6cb9443725d1e68194130533bfb04076(generated:0)
Error: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved type during parsing: javax.persistence.Column. To diagnose the issue you can use the --allow-incomplete-classpath option. The missing type is then reported at run time when it is accessed the first time.
Trace: 
        at parsing org.jooq.impl.Tools$9.apply(Tools.java:3556)
Call path from entry point to org.jooq.impl.Tools$9.apply(): 
        at org.jooq.impl.Tools$9.apply(Tools.java:3555)
        at org.jooq.impl.Tools$9.apply(Tools.java:3551)
        at org.jooq.impl.Tools$Cache.run(Tools.java:3181)
        at org.jooq.impl.DefaultRecordMapperProvider.provide(DefaultRecordMapperProvider.java:83)
        at com.oracle.svm.reflect.DefaultRecordMapperProvider_provide_1f8963e2e741d6be3b1656e5266fd0d5676700fe_576.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Method.java:566)
        at org.jboss.resteasy.core.ContextParameterInjector$GenericDelegatingProxy.invoke(ContextParameterInjector.java:122)
        at com.sun.proxy.$Proxy258.hashCode(Unknown Source)
        at java.util.HashMap.hash(HashMap.java:339)
        at java.util.HashMap.get(HashMap.java:552)
        at com.oracle.svm.jni.access.JNIReflectionDictionary.getClassObjectByName(JNIReflectionDictionary.java:128)
        at com.oracle.svm.jni.functions.JNIFunctions.FindClass(JNIFunctions.java:324)
        at com.oracle.svm.core.code.IsolateEnterStub.JNIFunctions_FindClass_3ec1032c6cb9443725d1e68194130533bfb04076(generated:0)
Error: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved type during parsing: javax.persistence.Entity. To diagnose the issue you can use the --allow-incomplete-classpath option. The missing type is then reported at run time when it is accessed the first time.
Trace: 
        at parsing org.jooq.impl.Tools$5.apply(Tools.java:3405)
Call path from entry point to org.jooq.impl.Tools$5.apply(): 
        at org.jooq.impl.Tools$5.apply(Tools.java:3401)
        at org.jooq.impl.Tools$5.apply(Tools.java:3397)
        at org.jooq.impl.Tools$Cache.run(Tools.java:3181)
        at org.jooq.impl.DefaultRecordMapperProvider.provide(DefaultRecordMapperProvider.java:83)
        at com.oracle.svm.reflect.DefaultRecordMapperProvider_provide_1f8963e2e741d6be3b1656e5266fd0d5676700fe_576.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Method.java:566)
        at org.jboss.resteasy.core.ContextParameterInjector$GenericDelegatingProxy.invoke(ContextParameterInjector.java:122)
        at com.sun.proxy.$Proxy258.hashCode(Unknown Source)
        at java.util.HashMap.hash(HashMap.java:339)
        at java.util.HashMap.get(HashMap.java:552)
        at com.oracle.svm.jni.access.JNIReflectionDictionary.getClassObjectByName(JNIReflectionDictionary.java:128)
        at com.oracle.svm.jni.functions.JNIFunctions.FindClass(JNIFunctions.java:324)
        at com.oracle.svm.core.code.IsolateEnterStub.JNIFunctions_FindClass_3ec1032c6cb9443725d1e68194130533bfb04076(generated:0)

        at com.oracle.svm.core.util.UserError.abort(UserError.java:79)
        at com.oracle.svm.hosted.FallbackFeature.reportAsFallback(FallbackFeature.java:217)
        at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:753)
        at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:538)
        at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:451)
        at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Caused by: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: Unsupported features in 4 methods
Detailed message:
Error: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved type during parsing: javax.persistence.Column. To diagnose the issue you can use the --allow-incomplete-classpath option. The missing type is then reported at run time when it is accessed the first time.
Trace: 
        at parsing org.jooq.impl.Tools$6.apply(Tools.java:3440)
Call path from entry point to org.jooq.impl.Tools$6.apply(): 
        at org.jooq.impl.Tools$6.apply(Tools.java:3437)
        at org.jooq.impl.Tools$6.apply(Tools.java:3433)
        at org.jooq.impl.Tools$Cache.run(Tools.java:3181)
        at org.jooq.impl.DefaultRecordMapperProvider.provide(DefaultRecordMapperProvider.java:83)
        at com.oracle.svm.reflect.DefaultRecordMapperProvider_provide_1f8963e2e741d6be3b1656e5266fd0d5676700fe_576.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Method.java:566)
        at org.jboss.resteasy.core.ContextParameterInjector$GenericDelegatingProxy.invoke(ContextParameterInjector.java:122)
        at com.sun.proxy.$Proxy258.hashCode(Unknown Source)
        at java.util.HashMap.hash(HashMap.java:339)
        at java.util.HashMap.get(HashMap.java:552)
        at com.oracle.svm.jni.access.JNIReflectionDictionary.getClassObjectByName(JNIReflectionDictionary.java:128)
        at com.oracle.svm.jni.functions.JNIFunctions.FindClass(JNIFunctions.java:324)
        at com.oracle.svm.core.code.IsolateEnterStub.JNIFunctions_FindClass_3ec1032c6cb9443725d1e68194130533bfb04076(generated:0)
Error: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved type during parsing: javax.persistence.Column. To diagnose the issue you can use the --allow-incomplete-classpath option. The missing type is then reported at run time when it is accessed the first time.
Trace: 
        at parsing org.jooq.impl.Tools$8.apply(Tools.java:3507)
Call path from entry point to org.jooq.impl.Tools$8.apply(): 
        at org.jooq.impl.Tools$8.apply(Tools.java:3504)
        at org.jooq.impl.Tools$8.apply(Tools.java:3500)
        at org.jooq.impl.Tools$Cache.run(Tools.java:3181)
        at org.jooq.impl.DefaultRecordMapperProvider.provide(DefaultRecordMapperProvider.java:83)
        at com.oracle.svm.reflect.DefaultRecordMapperProvider_provide_1f8963e2e741d6be3b1656e5266fd0d5676700fe_576.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Method.java:566)
        at org.jboss.resteasy.core.ContextParameterInjector$GenericDelegatingProxy.invoke(ContextParameterInjector.java:122)
        at com.sun.proxy.$Proxy258.hashCode(Unknown Source)
        at java.util.HashMap.hash(HashMap.java:339)
        at java.util.HashMap.get(HashMap.java:552)
        at com.oracle.svm.jni.access.JNIReflectionDictionary.getClassObjectByName(JNIReflectionDictionary.java:128)
        at com.oracle.svm.jni.functions.JNIFunctions.FindClass(JNIFunctions.java:324)
        at com.oracle.svm.core.code.IsolateEnterStub.JNIFunctions_FindClass_3ec1032c6cb9443725d1e68194130533bfb04076(generated:0)
Error: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved type during parsing: javax.persistence.Column. To diagnose the issue you can use the --allow-incomplete-classpath option. The missing type is then reported at run time when it is accessed the first time.
Trace: 
        at parsing org.jooq.impl.Tools$9.apply(Tools.java:3556)
Call path from entry point to org.jooq.impl.Tools$9.apply(): 
        at org.jooq.impl.Tools$9.apply(Tools.java:3555)
        at org.jooq.impl.Tools$9.apply(Tools.java:3551)
        at org.jooq.impl.Tools$Cache.run(Tools.java:3181)
        at org.jooq.impl.DefaultRecordMapperProvider.provide(DefaultRecordMapperProvider.java:83)
        at com.oracle.svm.reflect.DefaultRecordMapperProvider_provide_1f8963e2e741d6be3b1656e5266fd0d5676700fe_576.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Method.java:566)
        at org.jboss.resteasy.core.ContextParameterInjector$GenericDelegatingProxy.invoke(ContextParameterInjector.java:122)
        at com.sun.proxy.$Proxy258.hashCode(Unknown Source)
        at java.util.HashMap.hash(HashMap.java:339)
        at java.util.HashMap.get(HashMap.java:552)
        at com.oracle.svm.jni.access.JNIReflectionDictionary.getClassObjectByName(JNIReflectionDictionary.java:128)
        at com.oracle.svm.jni.functions.JNIFunctions.FindClass(JNIFunctions.java:324)
        at com.oracle.svm.core.code.IsolateEnterStub.JNIFunctions_FindClass_3ec1032c6cb9443725d1e68194130533bfb04076(generated:0)
Error: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved type during parsing: javax.persistence.Entity. To diagnose the issue you can use the --allow-incomplete-classpath option. The missing type is then reported at run time when it is accessed the first time.
Trace: 
        at parsing org.jooq.impl.Tools$5.apply(Tools.java:3405)
Call path from entry point to org.jooq.impl.Tools$5.apply(): 
        at org.jooq.impl.Tools$5.apply(Tools.java:3401)
        at org.jooq.impl.Tools$5.apply(Tools.java:3397)
        at org.jooq.impl.Tools$Cache.run(Tools.java:3181)
        at org.jooq.impl.DefaultRecordMapperProvider.provide(DefaultRecordMapperProvider.java:83)
        at com.oracle.svm.reflect.DefaultRecordMapperProvider_provide_1f8963e2e741d6be3b1656e5266fd0d5676700fe_576.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Method.java:566)
        at org.jboss.resteasy.core.ContextParameterInjector$GenericDelegatingProxy.invoke(ContextParameterInjector.java:122)
        at com.sun.proxy.$Proxy258.hashCode(Unknown Source)
        at java.util.HashMap.hash(HashMap.java:339)
        at java.util.HashMap.get(HashMap.java:552)
        at com.oracle.svm.jni.access.JNIReflectionDictionary.getClassObjectByName(JNIReflectionDictionary.java:128)
        at com.oracle.svm.jni.functions.JNIFunctions.FindClass(JNIFunctions.java:324)
        at com.oracle.svm.core.code.IsolateEnterStub.JNIFunctions_FindClass_3ec1032c6cb9443725d1e68194130533bfb04076(generated:0)

        at com.oracle.graal.pointsto.constraints.UnsupportedFeatures.report(UnsupportedFeatures.java:129)
        at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:750)
        ... 8 more
Error: Image build request failed with exit status 1

> Task :quarkusBuild FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':quarkusBuild'.
> io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkus.deployment.pkg.steps.NativeImageBuildStep#build threw an exception: java.lang.RuntimeException: Failed to build native image
        at io.quarkus.deployment.pkg.steps.NativeImageBuildStep.build(NativeImageBuildStep.java:366)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:932)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
        at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
        at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2046)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1578)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
        at java.base/java.lang.Thread.run(Thread.java:834)
        at org.jboss.threads.JBossThread.run(JBossThread.java:479)
  Caused by: java.lang.RuntimeException: Image generation failed. Exit code: 1
        at io.quarkus.deployment.pkg.steps.NativeImageBuildStep.imageGenerationFailed(NativeImageBuildStep.java:416)
        at io.quarkus.deployment.pkg.steps.NativeImageBuildStep.build(NativeImageBuildStep.java:344)
        ... 12 more
```

**Comment by angrymango** [comment]
It is missing javax.persistence. Adding this reference should fix it:

```groovy
compile group: 'org.hibernate.javax.persistence', name: 'hibernate-jpa-2.1-api', version: '1.0.0.Final'
```

Or for maven:

```xml
    <dependency>
      <groupId>org.hibernate.javax.persistence</groupId>
      <artifactId>hibernate-jpa-2.1-api</artifactId>
      <version>1.0.0.Final</version>
    </dependency>
```

I updated the readme to include this.

**Comment by itboy87** [comment]
@angrymango thanks it fixed but i have another error when I run native app. Check here https://github.com/angrymango/quarkus-ext-jooq/issues/2.
