### ISSUE TITLE
No matching constructor found on type class

### ISSUE THREAD

**Issue by itboy87** [angrymango/quarkus-ext-jooq#2]
Native app crashing when run any DB query. Genre is pojo class generated by jooq gradle from database.

```
No matching constructor found on type class com.example.jooq.tables.pojos.Genre for row type 
  "example_db"."genre"."genre_id", 
  "example_db"."genre"."genre_title"

	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1702)
	at io.smallrye.context.SmallRyeThreadContext$ContextualRunnable.run(SmallRyeThreadContext.java:56)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2046)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1578)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1426)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at java.lang.Thread.run(Thread.java:834)
	at org.jboss.threads.JBossThread.run(JBossThread.java:479)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:517)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
Caused by: org.jooq.exception.MappingException: No matching constructor found on type class com.example.jooq.tables.pojos.Genre for row type 
  "example_db"."genre"."genre_id", 
  "example_db"."genre"."genre_title"

	at org.jooq.impl.DefaultRecordMapper.init(DefaultRecordMapper.java:494)
	at org.jooq.impl.DefaultRecordMapper.<init>(DefaultRecordMapper.java:321)
	at org.jooq.impl.DefaultRecordMapper.<init>(DefaultRecordMapper.java:312)
	at org.jooq.impl.DefaultRecordMapperProvider$1.apply(DefaultRecordMapperProvider.java:86)
	at org.jooq.impl.DefaultRecordMapperProvider$1.apply(DefaultRecordMapperProvider.java:83)
	at org.jooq.impl.Tools$Cache.run(Tools.java:3201)
	at org.jooq.impl.DefaultRecordMapperProvider.provide(DefaultRecordMapperProvider.java:83)
	at org.jooq.impl.ResultImpl.into(ResultImpl.java:1281)
	at org.jooq.impl.AbstractResultQuery.fetchInto(AbstractResultQuery.java:1550)
	at org.jooq.impl.SelectImpl.fetchInto(SelectImpl.java:3746)
	at com.example.model.GenreModel.getAllGenres(GenreModel.kt:16)
	at com.example.model.GenreModel_ClientProxy.getAllGenres(GenreModel_ClientProxy.zig:305)
	at com.example.helper.CacheProvider.getAllGenres(CacheHelper.kt:122)
	at com.example.helper.CacheProvider_Subclass.getAllGenres$$superaccessor12(CacheProvider_Subclass.zig:2014)
	at com.example.helper.CacheProvider_Subclass$$function$$12.apply(CacheProvider_Subclass$$function$$12.zig:29)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
	at io.quarkus.cache.runtime.CacheResultInterceptor.lambda$intercept$0(CacheResultInterceptor.java:27)
	at io.quarkus.cache.runtime.caffeine.CaffeineCache$MappingSupplier.get(CaffeineCache.java:136)
	at io.quarkus.cache.runtime.caffeine.CaffeineCache.lambda$get$0(CaffeineCache.java:58)
	at com.github.benmanes.caffeine.cache.LocalAsyncCache.lambda$get$0(LocalAsyncCache.java:77)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	... 11 more

2020-07-22 06:01:10,346 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-4) HTTP Request to /mobile/genre/get_list failed, error id: f20b0609-75bd-4415-b344-15fd317ce8bb-1: org.jboss.resteasy.spi.UnhandledException: org.jooq.exception.MappingException: No matching constructor found on type class com.example.jooq.tables.pojos.Genre for row type 
  "example_db"."genre"."genre_id", 
  "example_db"."genre"."genre_title"

	at org.jboss.resteasy.core.ExceptionHandler.handleApplicationException(ExceptionHandler.java:106)
	at org.jboss.resteasy.core.ExceptionHandler.handleException(ExceptionHandler.java:372)
	at org.jboss.resteasy.core.SynchronousDispatcher.writeException(SynchronousDispatcher.java:216)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:515)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:259)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:160)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:163)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:245)
	at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:132)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.access$000(VertxRequestHandler.java:37)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler$1.run(VertxRequestHandler.java:94)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2046)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1578)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at java.lang.Thread.run(Thread.java:834)
	at org.jboss.threads.JBossThread.run(JBossThread.java:479)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:517)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
Caused by: org.jooq.exception.MappingException: No matching constructor found on type class com.example.jooq.tables.pojos.Genre for row type 
  "example_db"."genre"."genre_id", 
  "example_db"."genre"."genre_title"

	at org.jooq.impl.DefaultRecordMapper.init(DefaultRecordMapper.java:494)
	at org.jooq.impl.DefaultRecordMapper.<init>(DefaultRecordMapper.java:321)
	at org.jooq.impl.DefaultRecordMapper.<init>(DefaultRecordMapper.java:312)
	at org.jooq.impl.DefaultRecordMapperProvider$1.apply(DefaultRecordMapperProvider.java:86)
	at org.jooq.impl.DefaultRecordMapperProvider$1.apply(DefaultRecordMapperProvider.java:83)
	at org.jooq.impl.Tools$Cache.run(Tools.java:3201)
	at org.jooq.impl.DefaultRecordMapperProvider.provide(DefaultRecordMapperProvider.java:83)
	at org.jooq.impl.ResultImpl.into(ResultImpl.java:1281)
	at org.jooq.impl.AbstractResultQuery.fetchInto(AbstractResultQuery.java:1550)
	at org.jooq.impl.SelectImpl.fetchInto(SelectImpl.java:3746)
	at com.example.model.GenreModel.getAllGenres(GenreModel.kt:16)
	at com.example.model.GenreModel_ClientProxy.getAllGenres(GenreModel_ClientProxy.zig:305)
	at com.example.helper.CacheProvider.getAllGenres(CacheHelper.kt:122)
	at com.example.helper.CacheProvider_Subclass.getAllGenres$$superaccessor12(CacheProvider_Subclass.zig:2014)
	at com.example.helper.CacheProvider_Subclass$$function$$12.apply(CacheProvider_Subclass$$function$$12.zig:29)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
	at io.quarkus.cache.runtime.CacheResultInterceptor.lambda$intercept$0(CacheResultInterceptor.java:27)
	at io.quarkus.cache.runtime.caffeine.CaffeineCache$MappingSupplier.get(CaffeineCache.java:136)
	at io.quarkus.cache.runtime.caffeine.CaffeineCache.lambda$get$0(CaffeineCache.java:58)
	at com.github.benmanes.caffeine.cache.LocalAsyncCache.lambda$get$0(LocalAsyncCache.java:77)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at io.smallrye.context.SmallRyeThreadContext$ContextualRunnable.run(SmallRyeThreadContext.java:56)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2046)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1578)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1426)
	... 6 more
```

**Comment by angrymango** [comment]
Take a look at the Quarkus documentation for the answer: [https://quarkus.io/guides/writing-native-applications-tips](https://quarkus.io/guides/writing-native-applications-tips)

Specifically you need to understand how native complication works with reflected types. The error message is telling you that the type you created is not present in the native executable so jOOQ cannot create an instance of it. The easiest way to fix it is to add the annotation:

```java
@RegisterForReflection
public class Genre { ... }
```

**Comment by itboy87** [comment]
Hi thanks but these are auto generated jooq pojo classes these will keep
changing whenever we change schema. I think i needed to use
reflection-config.json. I will try that thanks
